[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_24"
manylinux-i686-image = "manylinux_2_24"
manylinux-pypy_x86_64-image = "manylinux_2_24"
manylinux-aarch64-image = "manylinux_2_24"
manylinux-ppc64le-image = "manylinux_2_24"
manylinux-s390x-image = "manylinux_2_24"
manylinux-pypy_aarch64-image = "manylinux_2_24"
manylinux-pypy_i686-image = "manylinux_2_24"

    [tool.cibuildwheel.linux]
    before-all = "bash {project}/scripts/prepare-linux.sh"

    [tool.cibuildwheel.macos]
    before-all = "bash {project}/scripts/prepare-macos.sh"

        [tool.cibuildwheel.macos.environment]
        PYICU_LFLAGS = "{project}build/lib/libicui18n.a:{project}build/lib/libicuuc.a:{project}build/lib/libicudata.a"
