name: Build

on: [push, pull_request]

env:
  PYICU_VERSION: 2.7.4
  ICU_VERSION: 69_1

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v2

      - name: Download source
        run: |
          mkdir -p src/
          PYICU_CFLAGS=dummy PYICU_LFLAGS=dummy pip download \
            --no-binary=:all: \
            --no-deps \
            --dest src/ \
            "PyICU==${{ env.PYICU_VERSION }}"
          tar -C "src/" -xmzf "src/PyICU-${{ env.PYICU_VERSION }}.tar.gz"

      - name: Patch source
        run: |
          patch --verbose -p1 -d "src/PyICU-${{ env.PYICU_VERSION }}" < pyicu.patch
          cp pyproject.toml src/PyICU-${{ env.PYICU_VERSION }}/

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.2
        with:
          package-dir: ./src/PyICU-${{ env.PYICU_VERSION }}/
        env:
          CIBW_ENVIRONMENT_LINUX: >
            PYICU_VERSION="${{ env.PYICU_VERSION }}"
            ICU_VERSION="${{ env.ICU_VERSION }}"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
